name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Update dependencies
      run: sudo apt-get update

    - uses: awalsh128/cache-apt-pkgs-action@latest
      with:
        packages: texlive-xetex biber texlive-full
        version: 1

    - name: Build
      run: bash ./build/build.sh

    - name: Generate tag
      run: echo "release_tag=`date '+%Y-%m-%d-%H%M%S'`" >> $GITHUB_ENV

    - uses: softprops/action-gh-release@v1
      with:
        prerelease: true
        tag_name: ${{ env.release_tag }}
        files: swim.pdf

