name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install dependencies
      run: sudo apt-get install texlive-xetex biber

    - name: Build
      run: bash ./build/build.sh

    - name: Generate tag
      run: echo "release_tag=`date '+%Y-%m-%d-%H%M%S'`" >> $GITHUB_ENV

    - uses: softprops/action-gh-release@v1
      with:
        prerelease: true
        tag_name: ${{ env.release_tag }}
        files: swim.pdf

