name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Build
      run: bash ./build/build.sh

    - uses: softprops/action-gh-release@v1
      with:
        prerelease: true
        files: swim.pdf

